version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "4001:3000"
    networks:
      - app_net
  backend:
    build:
      context: ./backend
    environment:
      - User=${User}
      - Host=db
      - Password=${Password}
      - Database=${Database}
    ports:
      - "4002:3001"
    depends_on:
      - db
    networks:
      - app_net

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: Password
      MYSQL_DATABASE: Database
      MYSQL_USER: User
      MYSQL_PASSWORD: Password
    volumes:
      - db_data:/var/lib/mysql
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
    networks:
      - app_net
    ports:
      - "4003:3306"

networks:
  app_net:

volumes:
  db_data: {}
